import { useState } from "react";
import { emitNotice, parseMoney, readRepairOrders, readStore, writeStore, type DataRow } from "./erp-store";
import { ErpButton, ErpHead, ErpPanel, ErpTable } from "./erp-ui";

export default function ErpDashboard() {
  const [tab, setTab] = useState("Shop Overview");
  const [punches, setPunches] = useState<DataRow[]>(() => readStore("time-punches", []));
  const [clockStatus, setClockStatus] = useState(localStorage.getItem("my-car-care-clock-status") || "Clocked Out");
  const orders = readRepairOrders();
  const transactions = readStore<DataRow[]>("transactions", []);
  const collected = transactions.reduce((total, row) => total + parseMoney(row.Amount), 0);
  const grouped = punches.reduce<Record<string, DataRow[]>>((all, row) => { const date = String(row.Date); all[date] = [...(all[date] || []), row]; return all; }, {});
  const timesheets = Object.entries(grouped).map(([date, rows]) => { const sorted = [...rows].sort((a, b) => String(a.Time).localeCompare(String(b.Time))); const first = sorted.find(row => row.Action === "Clock In"); const last = [...sorted].reverse().find(row => row.Action === "Clock Out"); const breaks = sorted.filter(row => row.Action === "Break").length * .5; const total = first && last ? Math.max(0, (new Date(String(last.Time)).getTime() - new Date(String(first.Time)).getTime()) / 3600000 - breaks) : 0; return { Date: date, "Time In": first ? new Date(String(first.Time)).toLocaleTimeString() : "—", "Time Out": last ? new Date(String(last.Time)).toLocaleTimeString() : "—", Breaks: `${breaks.toFixed(2)} hrs`, Total: `${total.toFixed(2)} hrs`, Status: last ? "Complete" : "Open" }; });
  const hours = timesheets.reduce((sum, row) => sum + Number(String(row.Total).split(" ")[0]), 0);
  const punch = (action: string, status: string) => { const next = [{ Employee: "Tariq Alam", Date: new Date().toLocaleDateString(), Action: action, Time: new Date().toISOString(), Approved: "Pending" }, ...punches]; setPunches(next); writeStore("time-punches", next); setClockStatus(status); localStorage.setItem("my-car-care-clock-status", status); emitNotice(status); };
  const tabs = ["Shop Overview", "Activity Feed", "My Hours", "My Timesheet", "My Commission"];
  return <><ErpHead title="Shop Dashboard" tabs={tabs} active={tab} onTab={setTab} />
    {tab === "Shop Overview" && <div className="sa-page"><div className="sa-metrics">{[["Car Count", orders.length], ["Pending Sales", `$${orders.filter(order => order.status !== "Posted").reduce((sum, order) => sum + order.amount, 0).toLocaleString()}`], ["Collected", `$${collected.toFixed(2)}`], ["ARO", `$${(orders.reduce((sum, order) => sum + order.amount, 0) / Math.max(orders.length, 1)).toFixed(2)}`], ["Close Ratio", "93%"]].map(([name, value]) => <ErpPanel key={name}><span>{name}</span><strong>{value}</strong></ErpPanel>)}</div><ErpPanel className="sa-chart"><div>{[25, 42, 68, 84, 55].map((height, index) => <figure key={height}><span style={{ height: `${height}%` }} /><figcaption>{["Estimate", "Working", "Completed", "Paid", "Posted"][index]}</figcaption></figure>)}</div></ErpPanel></div>}
    {tab === "Activity Feed" && <div className="sa-page"><ErpPanel className="sa-simple"><h2>Activity Feed</h2>{[...transactions.slice(0, 5).map(row => `${row.Type || "Payment"} ${row.Amount} on ${row.RO}`), ...orders.slice(0, 5).map(order => `${order.id} · ${order.customer} · ${order.status}`)].map(item => <p key={item}>{item}</p>)}</ErpPanel></div>}
    {tab === "My Hours" && <div className="sa-page"><div className="sa-time-hero"><ErpPanel><span>Current Status</span><strong>{clockStatus}</strong><div><ErpButton disabled={clockStatus === "Clocked In"} onClick={() => punch("Clock In", "Clocked In")}>Clock In</ErpButton><ErpButton secondary disabled={clockStatus !== "Clocked In"} onClick={() => punch("Break", "On Break")}>Start Break</ErpButton><ErpButton danger disabled={clockStatus === "Clocked Out"} onClick={() => punch("Clock Out", "Clocked Out")}>Clock Out</ErpButton></div></ErpPanel><ErpPanel><span>Biweekly Hours</span><strong>{hours.toFixed(2)}</strong><p>Attendance is separate from technician job clocks.</p></ErpPanel></div><ErpPanel><ErpTable rows={punches} columns={["Employee", "Date", "Action", "Time", "Approved"]} /></ErpPanel></div>}
    {tab === "My Timesheet" && <div className="sa-page"><div className="sa-metrics"><ErpPanel><span>Regular</span><strong>{Math.min(hours, 80).toFixed(2)}</strong></ErpPanel><ErpPanel><span>Overtime</span><strong>{Math.max(0, hours - 80).toFixed(2)}</strong></ErpPanel><ErpPanel><span>Unpaid Breaks</span><strong>{(punches.filter(row => row.Action === "Break").length * .5).toFixed(2)}</strong></ErpPanel></div><ErpPanel><ErpTable rows={timesheets} columns={["Date", "Time In", "Time Out", "Breaks", "Total", "Status"]} /></ErpPanel></div>}
    {tab === "My Commission" && <div className="sa-page"><div className="sa-metrics"><ErpPanel><span>Collected</span><strong>${collected.toFixed(2)}</strong></ErpPanel><ErpPanel><span>Gross Profit (55%)</span><strong>${(collected * .55).toFixed(2)}</strong></ErpPanel><ErpPanel><span>Rate</span><strong>1.5%</strong></ErpPanel><ErpPanel><span>Earnings</span><strong>${(collected * .55 * .015).toFixed(2)}</strong></ErpPanel></div><ErpPanel className="sa-simple"><h2>Commission Statement</h2><p>Collected gross profit excluding tax. Refunds automatically reverse earnings.</p><ErpButton onClick={() => emitNotice("Commission statement approved")}>Approve Statement</ErpButton></ErpPanel></div>}
  </>;
}
